/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regexmatcher;

/**
 *
 * @author simplex
 */
public class helpScreen extends javax.swing.JFrame {

    /**
     * Creates new form helpScreen
     */  
    public helpScreen() {
        initComponents();
        StringBuffer buff = new StringBuffer();
        
        buff.append("<html>");;
        buff.append(String.format("<body style='width: %s'>", helpText.getWidth()));
        buff.append("<h1>Regex Nedir?</h1>");
        buff.append("<p style='font-size: 10px;'>Düzenli ifadeler(regular expression), bir metni düzenlemek "
                + "yada metin içerisinden belli kurallara uyan alt metinler elde etmek için "
                + "kullandığımız bir dildir. Bir regular expression, string tipindeki karakter "
                + "topluluğuna uygulanır. Sonuç olarak <i>substringler</i> oluşur yada orjinal metnin bir "
                + "kısmını içeren değiştirilmiş yeni metinler elde edilir.</p>");
        buff.append("<h3>Nokta(.)</h3>");
        buff.append("<p style='font-size: 10px;'>Yeni satır karakteri(\\n) hariç herhangi tek bir karakterin yerini tutar.</p>");
        buff.append("<h3>Yılız(*)</h3>");
        buff.append("<p style='font-size: 10px;'>Bir ifadenin bütün tekrarlanmalarını bulur.</p>");
        buff.append("<p><i><b>doc yazamaya üşendim. Belki devam ederim.</b></i></p>");
        buff.append("</body>");
        buff.append("</html>");
        
        helpText.setText(buff.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        helpText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 450));
        setResizable(false);

        helpText.setText("tt");
        helpText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        helpText.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(helpText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(helpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(helpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(helpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(helpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new helpScreen().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel helpText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
